#' Rewriting of loadMetagenomicData in parkinsonsMetagenomicData
#'
#' This function should alegedly work faster and be more flexible toward
#' empty files. Additionally, it makes use of mia::importMetaphlan, which 
#' is constantly maintained tested. **IMPORTANT**: to work, the function must
#' have the right to write in its temporary directory. This code may not work in
#' some cloud computing environments.
#'
#' @param cache_table \code{data.frame} containing local paths where data have been 
#' cached with `cacheMetagenomicData`
#'
#' @returns A \code{TreeSummarizedExperiment} (without phylogenetic tree), as 
#' generated by `mia:importMetaPhlAn`.
#' 
#' @importFrom dplyr select mutate rename filter
#' @importFrom tidyr pivot_wider
#' @export
#'
#' @examples
#' 
#' # careful, this example takes a few minutes to run
#' \dontrun{
#' library(parkinsonsMetagenomicData)
#' 
#' human_parkinson_data <- dplyr::filter(sampleMetadata, !grepl("Mazmanian", study_name))
#' 
#' cached_profiles <- suppressMessages(cacheMetagenomicData(human_parkinson_data$uuid, data_type = "relative_abundance"))
#' 
#' is_downloaded <- sapply(cached_profiles$cache_path, file.exists)
#' 
#' table(is_downloaded)
#' 
#' cache_table <- cached_profiles[is_downloaded,]
#' 
#' # this one fails with this subset of samples
#' data.se <- loadMetagenomicData(cache_table)
#' 
#' # this one does not fail
#' data.tse <- loadMetagenomicData(cache_table)
#' }

loadMetagenomicData <- function(cache_table){
  
  files_to_read <- cache_table$cache_path
  names(files_to_read) <- cache_table$UUID
  
  # read first 8 lines of all files
  fileStats_headers <- lapply(files_to_read, function(filePath) readLines(filePath, 8))
  # extract metaphlan run information first N lines
  runInfo.list <- lapply(fileStats_headers, getMetaPhlAn_run_info)
  # get chocophlan version
  chocophlan_version <- unique(sapply(runInfo.list, "[[", "CHOCOPhlAn_version"))
  # get the run code
  metaphlan_run_command <- unique(sapply(runInfo.list, "[[", "metaphlan_command"))
  
  # check that the versions are uniform
  if((length(chocophlan_version) != 1) | (length(metaphlan_run_command) != 1)){
    stop(
      "Files were not run with one single CHOCOPhlAn version and/or run command."
    )
  }
  
  # make the colData
  colData.df <- dplyr::filter(parkinsonsMetagenomicData::sampleMetadata, uuid %in% cache_table$UUID)
  colData.df <- colData.df[match(names(runInfo.list), colData.df$uuid),]
  colData.df[["number_reads"]] <- as.integer(sapply(runInfo.list, "[[", "reads_processed"))
  rownames(colData.df) <- colData.df[["uuid"]]
  
  # find where profiles start (not too necessary, but it's a more flexible check)
  line_to_read_from <- grep("\\#clade_name|\\#ID", fileStats_headers[[1]])
  
  # define the columns to keep, hopefull this is compatible with metaphlan3, but it is not tested yet
  cols_all <- str_split(fileStats_headers[[1]][max(grep("#", fileStats_headers[[1]]))], pattern = "\\t")[[1]]
  cols_to_keep <- grep(c("clade|ID|abund|count"), cols_all, value = TRUE)
  
  # read file as raw input 
  input_raw.tb <- read_tsv(files_to_read, skip = 4, progress = FALSE, id = "fileName") |>
    # add uuid codes instead of cache
    dplyr::mutate(uuid = names(files_to_read)[match(fileName, files_to_read)]) |>
    # keep only columns we are interested in
    dplyr::select(all_of(c(cols_to_keep, "uuid")))
    
  colnames(input_raw.tb) <- gsub("#", "", colnames(input_raw.tb), fixed = TRUE)
  
  input_pivoted <- pivot_wider(data = input_raw.tb, names_from = "uuid", values_from = grep("abund|count", colnames(input_raw.tb), value = TRUE), values_fill = 0)
  tmpFile <- file.path(tempdir(), "profiles.tsv")
  write_tsv(input_pivoted, tmpFile)
  
  data.tse <- mia::importMetaPhlAn(tmpFile, col.data = colData.df)
  S4Vectors::metadata(data.tse)[["MetaPhlAn_run_info"]] <- list(
    "CHOCOPhlAn_version" = chocophlan_version, 
    "MetaPhlAn command" = metaphlan_run_command, 
    "reads_processed" = "see colData[['number_reads']]"
    )
  
  return(data.tse)
}



#' Extract run info of a MetaPhlAn run 
#'
#' @param mpaFile A \code{character} vector with the metaphlan profile already 
#' read into R with readLines
#'
#' @returns A \code{list} of MetaPhlAn run information (db version, code, reads)
#' @export
#'
#' @examples
#' 
#' \dontrun{
#' mpaProfile <- readLines("path/to/metaphlan_run.tsv")
#' 
#' mpa_run_info <- getMetaPhlAn_run_info(mpaProfile)
#' 
#' }
#' 
getMetaPhlAn_run_info <- function(mpaFile){
  
  mpaFile_run_info_raw <- mpaFile[startsWith(mpaFile, "#")]
  mpaFile_run_info_raw <- gsub("#", "", mpaFile_run_info_raw, fixed = TRUE)
  
  return(
    list(
      "CHOCOPhlAn_version" = mpaFile_run_info_raw[1],
      "MetaPhlAn command" = mpaFile_run_info_raw[2],
      "reads_processed" = gsub(" reads processed", "", mpaFile_run_info_raw[3],fixed = TRUE)
    )
  )
  
}


read_metaphlan_input <- function(path){
  
}


